### ISSUE TITLE
fix: logo looks really bad

### ISSUE THREAD

**Issue by wkaisertexas** [wkaisertexas/ScreenTimeLapse#15]
I am ashamed to say that the current logo is actually my second iteration. 

<img width="56" alt="Screenshot 2023-12-11 at 5 39 21 PM" src="https://github.com/wkaisertexas/ScreenTimeLapse/assets/27795014/fc908b23-0f72-40ab-8162-c99ba67f3ebf">

My goal will probably to make it more skeuomorphic and look like an actual camera or more glassmorphic. I really do not know. 

I hate graphic design.

**Comment by yArna** [comment]
I created an icon you can use as an app icon if you like


 

<img width="256" alt="image" src="https://github.com/wkaisertexas/ScreenTimeLapse/assets/82231420/69e268ba-9e27-4deb-aeed-bb32542261a5">



- Source File: [ScreenTimeLapse-icon.zip](https://github.com/wkaisertexas/ScreenTimeLapse/files/14550549/ScreenTimeLapse-icon.zip)

 

<img width="617" alt="image" src="https://github.com/wkaisertexas/ScreenTimeLapse/assets/82231420/7e55b8b7-7b22-41fa-b57f-f06b71efac7b">

**Comment by wkaisertexas** [comment]
That looks really good. 

I tried implementing the >>> to represent fast forwarding but the motif just does not work.

**Comment by yArna** [comment]
Maybe we can use the >>>  element as a texture

 
<img width="617" alt="image" src="https://github.com/wkaisertexas/ScreenTimeLapse/assets/82231420/591c387f-911e-404d-8e9f-c2302c71fccc">


 
<img width="256" alt="image" src="https://github.com/wkaisertexas/ScreenTimeLapse/assets/82231420/5a26fffd-596a-4ee7-a242-58f7f4228f54">

[It use Figma to edit](https://www.figma.com/file/Nd8ncxc9O9ggbpWkYDODKv/ScreenTimeLapse?type=design&node-id=1%3A2&mode=design&t=JwGLCW2eyqDysP6C-1)

**Comment by wkaisertexas** [comment]
![icon](https://github.com/wkaisertexas/ScreenTimeLapse/assets/27795014/3c742dd7-84cf-4057-ba51-a0344a54f35a)

The first one looks good. Incorporating the arrows was kind of a silly motif that I do not think works that well. However, I just adjusted the logo so you could not see a hard gradient and added a slight shadow. Thoughts?

**Comment by yArna** [comment]
Looks good too, choose what you like

**Comment by wkaisertexas** [comment]
You even setup the correct exports in the logo file. You are amazing!

**Comment by wkaisertexas** [comment]
Thank you so much for making the logo! @yArna
