### ISSUE TITLE
brew link is wrong

### ISSUE THREAD

**Issue by MohamedElashri** [wkaisertexas/ScreenTimeLapse#20]
Hi when you try to install via homebrew via 

```bash
brew install --cask https://raw.githubusercontent.com/wkaisertexas/ScreenTimeLapse/main/screentimelapse.rb
```
it will try to download this zip file (from github releases) 

```bash
https://github.com/wkaisertexas/ScreenTimeLapse/releases/download/v1.0.0/ScreenTimeLapse.zip
```

but the actual link (the name of zip file itself is different)

```bash
https://github.com/wkaisertexas/ScreenTimeLapse/releases/download/v1.0.0/TimeLapze.zip
```

**Comment by wkaisertexas** [comment]
Thanks for submitting the PR for this. Even though it is unpublished, someone claimed the name ScreenTimeLapse for the Apple app store which is annoying. Thanks for the PR!
