### ISSUE TITLE
Update README to clarify it is Mac only 

### ISSUE THREAD

**Issue by nmstoker** [wkaisertexas/ScreenTimeLapse#22]
Nice project!

One needs to read quite far before it's clear from the tech stack that this is Mac only. It would be good for transparency to make that clear at the top of the README (and to do so even if you aspire to later being cross platform at some point).

**Comment by wkaisertexas** [comment]
<img width="349" alt="Screenshot 2024-03-09 at 3 22 07 PM" src="https://github.com/wkaisertexas/ScreenTimeLapse/assets/27795014/6317c134-10b8-4100-bf54-d8b7c7726ecd">
<img width="84" alt="Screenshot 2024-03-09 at 3 21 54 PM" src="https://github.com/wkaisertexas/ScreenTimeLapse/assets/27795014/dfc92025-8bbe-43a3-b4a7-b4c20d6c1feb">

<img width="258" alt="Screenshot 2024-03-09 at 3 21 46 PM" src="https://github.com/wkaisertexas/ScreenTimeLapse/assets/27795014/1da8cef2-902d-4fbc-a3d9-045973c05b0b">

Trust me I would not be using XCode if I did not have to be 😂. I will add a note in the title, however.
