### ISSUE TITLE
Settings close when dock icon gets hidden

### ISSUE THREAD

**Issue by orimandel** [wkaisertexas/ScreenTimeLapse#27]
The order of events that happened is this:

1. I opened the menu from the menu bar icon
2. I opened the settings dialog from the menu
3. I selected the `Hide Icon In Dock`
4. The settings dialog **gets hidden along the app icon in dock**
5. I have to quit using the option in the menubar then reopen

Great app otherwise

**Comment by wkaisertexas** [comment]
What version of macos are you on?

**Comment by orimandel** [comment]
14.3 Beta

**Comment by wkaisertexas** [comment]
Okay, I have to fix then.

**Comment by wkaisertexas** [comment]
Fixed! Thanks
