### ISSUE TITLE
Deletes one of the two displays' videos??

### ISSUE THREAD

**Issue by orimandel** [wkaisertexas/ScreenTimeLapse#29]
I recorded a timelapze using two monitors (by accident, I only wanted to record the external one but both the external and the mac's display were selected in the menu). When finishing the 3hr long recording, QuickTime popped up showing the recording of the mac's screen, even though I have the setting disabled. no worries though.
Main problem is - the video of the external monitor is nowhere to be found! I looked in my selected location, it's simply not there and I am so bummed out.
Note: I also can not find the Mac display's vid, but using the QuickTime popup I can save it.

**Comment by wkaisertexas** [comment]
The video is always shown if it can not be saved to the directory specified (Desktop, Documents, etc.). That way you can see the video. From the Quicktime, you can resave the video to a location that you want (Desktop, Documents, etc.). However, without permission, MacOS does not let you save there directly.

I **WANTED** to save videos in the Movies folder if the user had not specified a location. However, Apple denied me the ability to add those permissions in the `info.plist` file to pass App Store review.

**Comment by wkaisertexas** [comment]
I will admit this interaction design is a little wonky, however.

**Comment by orimandel** [comment]
I get that, okay, but the problem still exists that one of the files did not even appear - the external monitor's video did not appear on QuickTime and did not get saved to the folder either. It seems like the problem with the workaround QT solution is that it only opens one file and not more - therefore one of my two files was lost.

**Comment by wkaisertexas** [comment]
Did you check the tmp folder itself?
