### ISSUE TITLE
Cannot set folder to save videos to

### ISSUE THREAD

**Issue by michaelsharman** [wkaisertexas/ScreenTimeLapse#32]
On Sonoma 14.4.1 (23E224), clicking the button to set the save location does nothing. You can't drag a location there either.

**Comment by wkaisertexas** [comment]
Hey, sorry about that. I forgot it is `@Published` instead of `@State` in an observed object. Will fix

**Comment by wkaisertexas** [comment]
This should be resolved, the new build is not pushed on the app store nor homebrew yet
