### ISSUE TITLE
App is $100 on Canadian App Store

### ISSUE THREAD

**Issue by Cale111** [wkaisertexas/ScreenTimeLapse#33]
The title is pretty self explanatory.
I'm not sure if it's like this in other regions, but I know that it's free on the US store.
<img width="394" alt="Screenshot 2024-04-07 at 16 41 07" src="https://github.com/wkaisertexas/ScreenTimeLapse/assets/34945905/9ce1158e-c6be-4538-b645-6beb654ae550">
https://apps.apple.com/ca/app/timelapze/id6473860445?mt=12

**Comment by wkaisertexas** [comment]
Not a bug.
