### ISSUE TITLE
Crashes after I press record

### ISSUE THREAD

**Issue by warek** [wkaisertexas/ScreenTimeLapse#34]
I installed the app through homebrew, ran it, changed some apps to not be recorded. Then I pressed record and the app crashes right away. Happens every time. 

I have two further monitors connected, disconnecting one didn't help. I also have enough disc space available.

Macbook Pro M1 Max and Ventura.

**Comment by wkaisertexas** [comment]
Hey, I am not too sure about this one. I will try and check crash logs after this but someone on HackerNews mentioned that they had problems on the M1 Max chip. They also claimed that it messed up their system so bad they needed a reboot.

Will definitely look into though

**Comment by warek** [comment]
Thanks! If you need my crash log to resolve this, let me know

**Comment by wkaisertexas** [comment]
I honestly, have no idea what this is. I am getting very sparse errors from XCode, so I think it maybe something hard-ware-software related. I will put a disclaimer somewhere

**Comment by rutmanz** [comment]
I also have this issue on an Intel Macbook Pro, using the latest release

**Comment by wkaisertexas** [comment]
Do you get a crash dialog or does the app just quit?

**Comment by rutmanz** [comment]
I get Apple's `TimeLapze quit unexpectedly` dialog, if that's what you're referring to. Immediately after pressing record the app disappears from the menu bar, and shortly after that, the problem report window appears

[Crash Report](https://github.com/user-attachments/files/16421716/report.txt)

**Comment by wkaisertexas** [comment]
Thanks for providing the crash report. I will look into this
