### ISSUE TITLE
Can't change recording directory on MacOS Sonoma 14.5

### ISSUE THREAD

**Issue by sackdan** [wkaisertexas/ScreenTimeLapse#55]
Installed via `brew install timelapze`

Whe clicking Settings, the Choose Output Folder does nothing.

**Comment by wkaisertexas** [comment]
I need to push a new version to homebrew. I am going to batch a couple of changes and do it

**Comment by Nickersoft** [comment]
Did you ever publish it @wkaisertexas? I'm running into this after a fresh Homebrew install :/
