### ISSUE TITLE
Recording framerate are off

### ISSUE THREAD

**Issue by rybinfx** [wkaisertexas/ScreenTimeLapse#57]
Hey guys! Set the settings to 60x faster, got full length output.
![Screenshot 2024-11-09 at 22 47 38](https://github.com/user-attachments/assets/5f5631d5-7332-4912-8db0-c1711221e065)
![Screenshot 2024-11-09 at 22 47 20](https://github.com/user-attachments/assets/76e0e0fb-2990-408b-b288-952716a6becc)
Also saving dir still doesn't work from homebrew..

**Comment by wkaisertexas** [comment]
Thanks for bringing this to my attention. I will get to work on this

**Comment by wkaisertexas** [comment]
This should be fixed in the new release, please let me know if it is not

**Comment by RyanKim17920** [comment]
I have a somewhat similar issue - the displayed length seems to be correct but the actual length of the video has the speed meter bar on the bottom which allows it to get back to a much longer video length causing there to be an excessively large file size. I'm on MacOS Sequoia Version 15.6.1 (24G90) if that is helpful:

File information: 
<img width="257" height="282" alt="Image" src="https://github.com/user-attachments/assets/4f7a9102-899c-485b-808e-463f7218a24d" />

The options seem to include the slower timelapse (seems to be around 5x timelapse speed) :

Slowest possible speed: <img width="471" height="103" alt="Image" src="https://github.com/user-attachments/assets/2985a086-0275-4f2b-b9f1-529de0e11c80" />

What it should be always: 

<img width="460" height="96" alt="Image" src="https://github.com/user-attachments/assets/27425038-79e3-4663-93d8-7d8abd5bbac0" />

**Comment by RyanKim17920** [comment]
@wkaisertexas Please reopen this issue, thank you!
